import sys
from tkinter import *
from tkinter import messagebox
import pandas as pd
import numpy as np

try:
    root = Tk()
    root.bg='gray'
    root.title('Modern Periodic Table')
    current_element = ''

    no = StringVar()
    name = StringVar()
    mass = StringVar()
    nature = StringVar()
    neutrons = StringVar()
    phase = StringVar()

    var1 = StringVar()
    var2 = StringVar()
    var3 = StringVar()
    var4 = StringVar()
    var5 = StringVar()
    var6 = StringVar()

    df = pd.read_csv(r'Elements.csv')

    def details_label():
        no.set('Atomic\nNo.:')
        name.set('Name:')
        mass.set('Mass:')
        nature.set('Nature:')
        neutrons.set('Neutr -\non No.:')
        phase.set('Phase:')


    def h():
        details_label()
        var1.set(df.loc[0,'AtomicNumber'])
        var2.set(df.loc[0,'Element'])
        var3.set(round(df.loc[0,'AtomicMass'],5))
        var4.set(df.loc[0,'Type'])
        var5.set(df.loc[0,'Phase'])
        var6.set(df.loc[0,'NumberofNeutrons'])


    def he():
        details_label()
        var5.set(df.loc[1,'Phase'])
        var6.set(df.loc[1,'NumberofNeutrons'])
        var1.set(df.loc[1,'AtomicNumber'])
        var2.set(df.loc[1,'Element'])
        var3.set(round(df.loc[1,'AtomicMass'],5))
        var4.set(df.loc[1,'Type'])
    def li():
        details_label()
        var5.set(df.loc[2,'Phase'])
        var6.set(df.loc[2,'NumberofNeutrons'])
        var1.set(df.loc[2,'AtomicNumber'])
        var2.set(df.loc[2,'Element'])
        var3.set(round(df.loc[2,'AtomicMass'],5))
        var4.set('Alkali\nMetal')
    def be():
        details_label()
        var5.set(df.loc[3,'Phase'])
        var6.set(df.loc[3,'NumberofNeutrons'])
        var1.set(df.loc[3,'AtomicNumber'])
        var2.set(df.loc[3,'Element'])
        var3.set(round(df.loc[3,'AtomicMass'],5))
        var4.set('Alkaline\nEarthMetal')
    def b():
        details_label()
        var5.set(df.loc[4,'Phase'])
        var6.set(df.loc[4,'NumberofNeutrons'])
        var1.set(df.loc[4,'AtomicNumber'])
        var2.set(df.loc[4,'Element'])
        var3.set(round(df.loc[4,'AtomicMass'],5))
        var4.set(df.loc[4,'Type'])
    def c():
        details_label()
        var5.set(df.loc[5,'Phase'])
        var6.set(df.loc[5,'NumberofNeutrons'])
        var1.set(df.loc[5,'AtomicNumber'])
        var2.set(df.loc[5,'Element'])
        var3.set(round(df.loc[5,'AtomicMass'],5))
        var4.set(df.loc[5,'Type'])
    def n():
        details_label()
        var5.set(df.loc[6,'Phase'])
        var6.set(df.loc[6,'NumberofNeutrons'])
        var1.set(df.loc[6,'AtomicNumber'])
        var2.set(df.loc[6,'Element'])
        var3.set(round(df.loc[6,'AtomicMass'],5))
        var4.set(df.loc[6,'Type'])
    def o():
        details_label()
        var5.set(df.loc[7,'Phase'])
        var6.set(df.loc[7,'NumberofNeutrons'])
        var1.set(df.loc[7,'AtomicNumber'])
        var2.set(df.loc[7,'Element'])
        var3.set(round(df.loc[7,'AtomicMass'],5))
        var4.set(df.loc[7,'Type'])
    def f():
        details_label()
        var5.set(df.loc[8,'Phase'])
        var6.set(df.loc[8,'NumberofNeutrons'])
        var1.set(df.loc[8,'AtomicNumber'])
        var2.set(df.loc[8,'Element'])
        var3.set(round(df.loc[8,'AtomicMass'],5))
        var4.set(df.loc[8,'Type'])
    def Ne():
        details_label()
        var5.set(df.loc[9,'Phase'])
        var6.set(df.loc[9,'NumberofNeutrons'])
        var1.set(df.loc[9,'AtomicNumber'])
        var2.set(df.loc[9,'Element'])
        var3.set(round(df.loc[9,'AtomicMass'],5))
        var4.set(df.loc[9,'Type'])
    def na():
        details_label()
        var5.set(df.loc[10,'Phase'])
        var6.set(df.loc[10,'NumberofNeutrons'])
        var1.set(df.loc[10,'AtomicNumber'])
        var2.set(df.loc[10,'Element'])
        var3.set(round(df.loc[10,'AtomicMass'],5))
        var4.set('Alkali\nMetal')
    def mg():
        details_label()
        var5.set(df.loc[11,'Phase'])
        var6.set(df.loc[11,'NumberofNeutrons'])
        var1.set(df.loc[11,'AtomicNumber'])
        var2.set(df.loc[11,'Element'])
        var3.set(round(df.loc[11,'AtomicMass'],5))
        var4.set('Alkaline\nEarthMetal')
    def al():
        details_label()
        var5.set(df.loc[12,'Phase'])
        var6.set(df.loc[12,'NumberofNeutrons'])
        var1.set(df.loc[12,'AtomicNumber'])
        var2.set(df.loc[12,'Element'])
        var3.set(round(df.loc[12,'AtomicMass'],5))
        var4.set(df.loc[12,'Type'])
    def si():
        details_label()
        var5.set(df.loc[13,'Phase'])
        var6.set(df.loc[13,'NumberofNeutrons'])
        var1.set(df.loc[13,'AtomicNumber'])
        var2.set(df.loc[13,'Element'])
        var3.set(round(df.loc[13,'AtomicMass'],5))
        var4.set(df.loc[13,'Type'])
    def p():
        details_label()
        var5.set(df.loc[14,'Phase'])
        var6.set(df.loc[14,'NumberofNeutrons'])
        var1.set(df.loc[14,'AtomicNumber'])
        var2.set(df.loc[14,'Element'])
        var3.set(round(df.loc[14,'AtomicMass'],5))
        var4.set(df.loc[14,'Type'])
    def s():
        details_label()
        var5.set(df.loc[15,'Phase'])
        var6.set(df.loc[15,'NumberofNeutrons'])
        var1.set(df.loc[15,'AtomicNumber'])
        var2.set(df.loc[15,'Element'])
        var3.set(round(df.loc[15,'AtomicMass'],5))
        var4.set(df.loc[15,'Type'])
    def cl():
        details_label()
        var5.set(df.loc[16,'Phase'])
        var6.set(df.loc[16,'NumberofNeutrons'])
        var1.set(df.loc[16,'AtomicNumber'])
        var2.set(df.loc[16,'Element'])
        var3.set(round(df.loc[16,'AtomicMass'],5))
        var4.set(df.loc[16,'Type'])
    def ar():
        details_label()
        var5.set(df.loc[17,'Phase'])
        var6.set(df.loc[17,'NumberofNeutrons'])
        var1.set(df.loc[17,'AtomicNumber'])
        var2.set(df.loc[17,'Element'])
        var3.set(round(df.loc[17,'AtomicMass'],5))
        var4.set(df.loc[17,'Type'])
    def k():
        details_label()
        var5.set(df.loc[18,'Phase'])
        var6.set(df.loc[18,'NumberofNeutrons'])
        var1.set(df.loc[18,'AtomicNumber'])
        var2.set(df.loc[18,'Element'])
        var3.set(round(df.loc[18,'AtomicMass'],5))
        var4.set('Alkali\nMetal')
    def ca():
        details_label()
        var5.set(df.loc[19,'Phase'])
        var6.set(df.loc[19,'NumberofNeutrons'])
        var1.set(df.loc[19,'AtomicNumber'])
        var2.set(df.loc[19,'Element'])
        var3.set(round(df.loc[19,'AtomicMass'],5))
        var4.set('Alkaline\nEarthMetal')
    def sc():
        details_label()
        var5.set(df.loc[20,'Phase'])
        var6.set(df.loc[20,'NumberofNeutrons'])
        var1.set(df.loc[20,'AtomicNumber'])
        var2.set(df.loc[20,'Element'])
        var3.set(round(df.loc[20,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def ti():
        details_label()
        var5.set(df.loc[21,'Phase'])
        var6.set(df.loc[21,'NumberofNeutrons'])
        var1.set(df.loc[21,'AtomicNumber'])
        var2.set(df.loc[21,'Element'])
        var3.set(round(df.loc[21,'AtomicMass'],5))
        var4.set(df.loc[21,'Type'])
    def v():
        details_label()
        var5.set(df.loc[22,'Phase'])
        var6.set(df.loc[22,'NumberofNeutrons'])
        var1.set(df.loc[22,'AtomicNumber'])
        var2.set(df.loc[22,'Element'])
        var3.set(round(df.loc[22,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def cr():
        details_label()
        var5.set(df.loc[23,'Phase'])
        var6.set(df.loc[23,'NumberofNeutrons'])
        var1.set(df.loc[23,'AtomicNumber'])
        var2.set(df.loc[23,'Element'])
        var3.set(round(df.loc[23,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def mn():
        details_label()
        var5.set(df.loc[24,'Phase'])
        var6.set(df.loc[24,'NumberofNeutrons'])
        var1.set(df.loc[24,'AtomicNumber'])
        var2.set(df.loc[24,'Element'])
        var3.set(round(df.loc[24,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def fe():
        details_label()
        var5.set(df.loc[25,'Phase'])
        var6.set(df.loc[25,'NumberofNeutrons'])
        var1.set(df.loc[25,'AtomicNumber'])
        var2.set(df.loc[25,'Element'])
        var3.set(round(df.loc[25,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def co():
        details_label()
        var5.set(df.loc[26,'Phase'])
        var6.set(df.loc[26,'NumberofNeutrons'])
        var1.set(df.loc[26,'AtomicNumber'])
        var2.set(df.loc[26,'Element'])
        var3.set(round(df.loc[26,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def ni():
        details_label()
        var5.set(df.loc[27,'Phase'])
        var6.set(df.loc[27,'NumberofNeutrons'])
        var1.set(df.loc[27,'AtomicNumber'])
        var2.set(df.loc[27,'Element'])
        var3.set(round(df.loc[27,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def cu():
        details_label()
        var5.set(df.loc[28,'Phase'])
        var6.set(df.loc[28,'NumberofNeutrons'])
        var1.set(df.loc[28,'AtomicNumber'])
        var2.set(df.loc[28,'Element'])
        var3.set(round(df.loc[28,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def zn():
        details_label()
        var5.set(df.loc[29,'Phase'])
        var6.set(df.loc[29,'NumberofNeutrons'])
        var1.set(df.loc[29,'AtomicNumber'])
        var2.set(df.loc[29,'Element'])
        var3.set(round(df.loc[29,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def ga():
        details_label()
        var5.set(df.loc[30,'Phase'])
        var6.set(df.loc[30,'NumberofNeutrons'])
        var1.set(df.loc[30,'AtomicNumber'])
        var2.set(df.loc[30,'Element'])
        var3.set(round(df.loc[30,'AtomicMass'],5))
        var4.set(df.loc[30,'Type'])
    def ge():
        details_label()
        var5.set(df.loc[31,'Phase'])
        var6.set(df.loc[31,'NumberofNeutrons'])
        var1.set(df.loc[31,'AtomicNumber'])
        var2.set(df.loc[31,'Element'])
        var3.set(round(df.loc[31,'AtomicMass'],5))
        var4.set(df.loc[31,'Type'])
    def ars():
        details_label()
        var5.set(df.loc[32,'Phase'])
        var6.set(df.loc[32,'NumberofNeutrons'])
        var1.set(df.loc[32,'AtomicNumber'])
        var2.set(df.loc[32,'Element'])
        var3.set(round(df.loc[32,'AtomicMass'],5))
        var4.set(df.loc[32,'Type'])
    def se():
        details_label()
        var5.set(df.loc[33,'Phase'])
        var6.set(df.loc[33,'NumberofNeutrons'])
        var1.set(df.loc[33,'AtomicNumber'])
        var2.set(df.loc[33,'Element'])
        var3.set(round(df.loc[33,'AtomicMass'],5))
        var4.set(df.loc[33,'Type'])
    def br():
        details_label()
        var5.set(df.loc[34,'Phase'])
        var6.set(df.loc[34,'NumberofNeutrons'])
        var1.set(df.loc[34,'AtomicNumber'])
        var2.set(df.loc[34,'Element'])
        var3.set(round(df.loc[34,'AtomicMass'],5))
        var4.set(df.loc[34,'Type'])
    def kr():
        details_label()
        var5.set(df.loc[35,'Phase'])
        var6.set(df.loc[35,'NumberofNeutrons'])
        var1.set(df.loc[35,'AtomicNumber'])
        var2.set(df.loc[35,'Element'])
        var3.set(round(df.loc[35,'AtomicMass'],5))
        var4.set(df.loc[35,'Type'])
    def rb():
        details_label()
        var5.set(df.loc[36,'Phase'])
        var6.set(df.loc[36,'NumberofNeutrons'])
        var1.set(df.loc[36,'AtomicNumber'])
        var2.set(df.loc[36,'Element'])
        var3.set(round(df.loc[36,'AtomicMass'],5))
        var4.set('Alkali\nMetal')
    def sr():
        details_label()
        var5.set(df.loc[37,'Phase'])
        var6.set(df.loc[37,'NumberofNeutrons'])
        var1.set(df.loc[37,'AtomicNumber'])
        var2.set(df.loc[37,'Element'])
        var3.set(round(df.loc[37,'AtomicMass'],5))
        var4.set('Alkaline\nEarthMetal')
    def y():
        details_label()
        var5.set(df.loc[38,'Phase'])
        var6.set(df.loc[38,'NumberofNeutrons'])
        var1.set(df.loc[38,'AtomicNumber'])
        var2.set(df.loc[38,'Element'])
        var3.set(round(df.loc[38,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def zr():
        details_label()
        var5.set(df.loc[39,'Phase'])
        var6.set(df.loc[39,'NumberofNeutrons'])
        var1.set(df.loc[39,'AtomicNumber'])
        var2.set(df.loc[39,'Element'])
        var3.set(round(df.loc[39,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def nb():
        details_label()
        var5.set(df.loc[40,'Phase'])
        var6.set(df.loc[40,'NumberofNeutrons'])
        var1.set(df.loc[40,'AtomicNumber'])
        var2.set(df.loc[40,'Element'])
        var3.set(round(df.loc[40,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def mo():
        details_label()
        var5.set(df.loc[41,'Phase'])
        var6.set(df.loc[41,'NumberofNeutrons'])
        var1.set(df.loc[41,'AtomicNumber'])
        var2.set('Molybde-\nnum')
        var3.set(round(df.loc[41,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def tc():
        details_label()
        var5.set(df.loc[42,'Phase'])
        var6.set(df.loc[42,'NumberofNeutrons'])
        var1.set(df.loc[42,'AtomicNumber'])
        var2.set(df.loc[42,'Element'])
        var3.set(round(df.loc[42,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def ru():
        details_label()
        var5.set(df.loc[43,'Phase'])
        var6.set(df.loc[43,'NumberofNeutrons'])
        var1.set(df.loc[43,'AtomicNumber'])
        var2.set(df.loc[43,'Element'])
        var3.set(round(df.loc[43,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def rh():
        details_label()
        var5.set(df.loc[44,'Phase'])
        var6.set(df.loc[44,'NumberofNeutrons'])
        var1.set(df.loc[44,'AtomicNumber'])
        var2.set(df.loc[44,'Element'])
        var3.set(round(df.loc[44,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def Pd():
        details_label()
        var5.set(df.loc[45,'Phase'])
        var6.set(df.loc[45,'NumberofNeutrons'])
        var1.set(df.loc[45,'AtomicNumber'])
        var2.set(df.loc[45,'Element'])
        var3.set(round(df.loc[45,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def ag():
        details_label()
        var5.set(df.loc[46,'Phase'])
        var6.set(df.loc[46,'NumberofNeutrons'])
        var1.set(df.loc[46,'AtomicNumber'])
        var2.set(df.loc[46,'Element'])
        var3.set(round(df.loc[46,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def cd():
        details_label()
        var5.set(df.loc[47,'Phase'])
        var6.set(df.loc[47,'NumberofNeutrons'])
        var1.set(df.loc[47,'AtomicNumber'])
        var2.set(df.loc[47,'Element'])
        var3.set(round(df.loc[47,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def In():
        details_label()
        var5.set(df.loc[48,'Phase'])
        var6.set(df.loc[48,'NumberofNeutrons'])
        var1.set(df.loc[48,'AtomicNumber'])
        var2.set(df.loc[48,'Element'])
        var3.set(round(df.loc[48,'AtomicMass'],5))
        var4.set(df.loc[48,'Type'])
    def sn():
        details_label()
        var5.set(df.loc[49,'Phase'])
        var6.set(df.loc[49,'NumberofNeutrons'])
        var1.set(df.loc[49,'AtomicNumber'])
        var2.set(df.loc[49,'Element'])
        var3.set(round(df.loc[49,'AtomicMass'],5))
        var4.set(df.loc[49,'Type'])
    def sb():
        details_label()
        var5.set(df.loc[50,'Phase'])
        var6.set(df.loc[50,'NumberofNeutrons'])
        var1.set(df.loc[50,'AtomicNumber'])
        var2.set(df.loc[50,'Element'])
        var3.set(round(df.loc[50,'AtomicMass'],5))
        var4.set(df.loc[50,'Type'])
    def te():
        details_label()
        var5.set(df.loc[51,'Phase'])
        var6.set(df.loc[51,'NumberofNeutrons'])
        var1.set(df.loc[51,'AtomicNumber'])
        var2.set(df.loc[51,'Element'])
        var3.set(round(df.loc[51,'AtomicMass'],5))
        var4.set(df.loc[51,'Type'])
    def i():
        details_label()
        var5.set(df.loc[52,'Phase'])
        var6.set(df.loc[52,'NumberofNeutrons'])
        var1.set(df.loc[52,'AtomicNumber'])
        var2.set(df.loc[52,'Element'])
        var3.set(round(df.loc[52,'AtomicMass'],5))
        var4.set(df.loc[52,'Type'])
    def xe():
        details_label()
        var5.set(df.loc[53,'Phase'])
        var6.set(df.loc[53,'NumberofNeutrons'])
        var1.set(df.loc[53,'AtomicNumber'])
        var2.set(df.loc[53,'Element'])
        var3.set(round(df.loc[53,'AtomicMass'],5))
        var4.set(df.loc[53,'Type'])
    def cs():
        details_label()
        var5.set(df.loc[54,'Phase'])
        var6.set(df.loc[54,'NumberofNeutrons'])
        var1.set(df.loc[54,'AtomicNumber'])
        var2.set(df.loc[54,'Element'])
        var3.set(round(df.loc[54,'AtomicMass'],5))
        var4.set('Alkali\nMetal')
    def ba():
        details_label()
        var5.set(df.loc[55,'Phase'])
        var6.set(df.loc[55,'NumberofNeutrons'])
        var1.set(df.loc[55,'AtomicNumber'])
        var2.set(df.loc[55,'Element'])
        var3.set(round(df.loc[55,'AtomicMass'],5))
        var4.set('Alkaline\nEarthMetal')
    def la():
        details_label()
        var5.set(df.loc[56,'Phase'])
        var6.set(df.loc[56,'NumberofNeutrons'])
        var1.set(df.loc[56,'AtomicNumber'])
        var2.set(df.loc[56,'Element'])
        var3.set(round(df.loc[56,'AtomicMass'],5))
        var4.set(df.loc[56,'Type'])
    def ce():
        details_label()
        var5.set(df.loc[57,'Phase'])
        var6.set(df.loc[57,'NumberofNeutrons'])
        var1.set(df.loc[57,'AtomicNumber'])
        var2.set(df.loc[57,'Element'])
        var3.set(round(df.loc[57,'AtomicMass'],5))
        var4.set(df.loc[57,'Type'])
    def pr():
        details_label()
        var5.set(df.loc[58,'Phase'])
        var6.set(df.loc[58,'NumberofNeutrons'])
        var1.set(df.loc[58,'AtomicNumber'])
        var2.set('Praseody-\nmium')
        var3.set(round(df.loc[58,'AtomicMass'],5))
        var4.set(df.loc[58,'Type'])
    def nd():
        details_label()
        var5.set(df.loc[59,'Phase'])
        var6.set(df.loc[59,'NumberofNeutrons'])
        var1.set(df.loc[59,'AtomicNumber'])
        var2.set('Neody-\nmium')
        var3.set(round(df.loc[59,'AtomicMass'],5))
        var4.set(df.loc[59,'Type'])
    def pm():
        details_label()
        var5.set(df.loc[60,'Phase'])
        var6.set(df.loc[60,'NumberofNeutrons'])
        var1.set(df.loc[60,'AtomicNumber'])
        var2.set(df.loc[60,'Element'])
        var3.set(round(df.loc[60,'AtomicMass'],5))
        var4.set(df.loc[60,'Type'])
    def sm():
        details_label()
        var5.set(df.loc[61,'Phase'])
        var6.set(df.loc[61,'NumberofNeutrons'])
        var1.set(df.loc[61,'AtomicNumber'])
        var2.set(df.loc[61,'Element'])
        var3.set(round(df.loc[61,'AtomicMass'],5))
        var4.set(df.loc[61,'Type'])
    def eu():
        details_label()
        var5.set(df.loc[62,'Phase'])
        var6.set(df.loc[62,'NumberofNeutrons'])
        var1.set(df.loc[62,'AtomicNumber'])
        var2.set(df.loc[62,'Element'])
        var3.set(round(df.loc[62,'AtomicMass'],5))
        var4.set(df.loc[62,'Type'])
    def gd():
        details_label()
        var5.set(df.loc[63,'Phase'])
        var6.set(df.loc[63,'NumberofNeutrons'])
        var1.set(df.loc[63,'AtomicNumber'])
        var2.set(df.loc[63,'Element'])
        var3.set(round(df.loc[63,'AtomicMass'],5))
        var4.set(df.loc[63,'Type'])
    def tb():
        details_label()
        var5.set(df.loc[64,'Phase'])
        var6.set(df.loc[64,'NumberofNeutrons'])
        var1.set(df.loc[64,'AtomicNumber'])
        var2.set(df.loc[64,'Element'])
        var3.set(round(df.loc[64,'AtomicMass'],5))
        var4.set(df.loc[64,'Type'])
    def dy():
        details_label()
        var5.set(df.loc[65,'Phase'])
        var6.set(df.loc[65,'NumberofNeutrons'])
        var1.set(df.loc[65,'AtomicNumber'])
        var2.set(df.loc[65,'Element'])
        var3.set(round(df.loc[65,'AtomicMass'],5))
        var4.set(df.loc[65,'Type'])
    def ho():
        details_label()
        var5.set(df.loc[66,'Phase'])
        var6.set(df.loc[66,'NumberofNeutrons'])
        var1.set(df.loc[66,'AtomicNumber'])
        var2.set(df.loc[66,'Element'])
        var3.set(round(df.loc[66,'AtomicMass'],5))
        var4.set(df.loc[66,'Type'])
    def er():
        details_label()
        var5.set(df.loc[67,'Phase'])
        var6.set(df.loc[67,'NumberofNeutrons'])
        var1.set(df.loc[67,'AtomicNumber'])
        var2.set(df.loc[67,'Element'])
        var3.set(round(df.loc[67,'AtomicMass'],5))
        var4.set(df.loc[67,'Type'])
    def tm():
        details_label()
        var5.set(df.loc[68,'Phase'])
        var6.set(df.loc[68,'NumberofNeutrons'])
        var1.set(df.loc[68,'AtomicNumber'])
        var2.set(df.loc[68,'Element'])
        var3.set(round(df.loc[68,'AtomicMass'],5))
        var4.set(df.loc[68,'Type'])
    def yb():
        details_label()
        var5.set(df.loc[69,'Phase'])
        var6.set(df.loc[69,'NumberofNeutrons'])
        var1.set(df.loc[69,'AtomicNumber'])
        var2.set(df.loc[69,'Element'])
        var3.set(round(df.loc[69,'AtomicMass'],5))
        var4.set(df.loc[69,'Type'])
    def lu():
        details_label()
        var5.set(df.loc[70,'Phase'])
        var6.set(df.loc[70,'NumberofNeutrons'])
        var1.set(df.loc[70,'AtomicNumber'])
        var2.set(df.loc[70,'Element'])
        var3.set(round(df.loc[70,'AtomicMass'],5))
        var4.set(df.loc[70,'Type'])
    def hf():
        details_label()
        var5.set(df.loc[71,'Phase'])
        var6.set(df.loc[71,'NumberofNeutrons'])
        var1.set(df.loc[71,'AtomicNumber'])
        var2.set(df.loc[71,'Element'])
        var3.set(round(df.loc[71,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def ta():
        details_label()
        var5.set(df.loc[72,'Phase'])
        var6.set(df.loc[72,'NumberofNeutrons'])
        var1.set(df.loc[72,'AtomicNumber'])
        var2.set(df.loc[72,'Element'])
        var3.set(round(df.loc[72,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def w():
        details_label()
        var5.set(df.loc[73,'Phase'])
        var6.set(df.loc[73,'NumberofNeutrons'])
        var1.set(df.loc[73,'AtomicNumber'])
        var2.set(df.loc[73,'Element'])
        var3.set(round(df.loc[73,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def Re():
        details_label()
        var5.set(df.loc[74,'Phase'])
        var6.set(df.loc[74,'NumberofNeutrons'])
        var1.set(df.loc[74,'AtomicNumber'])
        var2.set(df.loc[74,'Element'])
        var3.set(round(df.loc[74,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def Os():
        details_label()
        var5.set(df.loc[75,'Phase'])
        var6.set(df.loc[75,'NumberofNeutrons'])
        var1.set(df.loc[75,'AtomicNumber'])
        var2.set(df.loc[75,'Element'])
        var3.set(round(df.loc[75,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def ir():
        details_label()
        var5.set(df.loc[76,'Phase'])
        var6.set(df.loc[76,'NumberofNeutrons'])
        var1.set(df.loc[76,'AtomicNumber'])
        var2.set(df.loc[76,'Element'])
        var3.set(round(df.loc[76,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def pt():
        details_label()
        var5.set(df.loc[77,'Phase'])
        var6.set(df.loc[77,'NumberofNeutrons'])
        var1.set(df.loc[77,'AtomicNumber'])
        var2.set(df.loc[77,'Element'])
        var3.set(round(df.loc[77,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def au():
        details_label()
        var5.set(df.loc[78,'Phase'])
        var6.set(df.loc[78,'NumberofNeutrons'])
        var1.set(df.loc[78,'AtomicNumber'])
        var2.set(df.loc[78,'Element'])
        var3.set(round(df.loc[78,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def hg():
        details_label()
        var5.set(df.loc[79,'Phase'])
        var6.set(df.loc[79,'NumberofNeutrons'])
        var1.set(df.loc[79,'AtomicNumber'])
        var2.set(df.loc[79,'Element'])
        var3.set(round(df.loc[79,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def ti():
        details_label()
        var5.set(df.loc[80,'Phase'])
        var6.set(df.loc[80,'NumberofNeutrons'])
        var1.set(df.loc[80,'AtomicNumber'])
        var2.set(df.loc[80,'Element'])
        var3.set(round(df.loc[80,'AtomicMass'],5))
        var4.set(df.loc[80,'Type'])
    def pb():
        details_label()
        var5.set(df.loc[81,'Phase'])
        var6.set(df.loc[81,'NumberofNeutrons'])
        var1.set(df.loc[81,'AtomicNumber'])
        var2.set(df.loc[81,'Element'])
        var3.set(round(df.loc[81,'AtomicMass'],5))
        var4.set(df.loc[81,'Type'])
    def bi():
        details_label()
        var5.set(df.loc[82,'Phase'])
        var6.set(df.loc[82,'NumberofNeutrons'])
        var1.set(df.loc[82,'AtomicNumber'])
        var2.set(df.loc[82,'Element'])
        var3.set(round(df.loc[82,'AtomicMass'],5))
        var4.set(df.loc[82,'Type'])
    def po():
        details_label()
        var5.set(df.loc[83,'Phase'])
        var6.set(df.loc[83,'NumberofNeutrons'])
        var1.set(df.loc[83,'AtomicNumber'])
        var2.set(df.loc[83,'Element'])
        var3.set(round(df.loc[83,'AtomicMass'],5))
        var4.set(df.loc[83,'Type'])
    def at():
        details_label()
        var5.set(df.loc[84,'Phase'])
        var6.set(df.loc[84,'NumberofNeutrons'])
        var1.set(df.loc[84,'AtomicNumber'])
        var2.set(df.loc[84,'Element'])
        var3.set(round(df.loc[84,'AtomicMass'],5))
        var4.set(df.loc[84,'Type'])
    def rn():
        details_label()
        var5.set(df.loc[85,'Phase'])
        var6.set(df.loc[85,'NumberofNeutrons'])
        var1.set(df.loc[85,'AtomicNumber'])
        var2.set(df.loc[85,'Element'])
        var3.set(round(df.loc[85,'AtomicMass'],5))
        var4.set(df.loc[85,'Type'])
    def fr():
        details_label()
        var5.set(df.loc[86,'Phase'])
        var6.set(df.loc[86,'NumberofNeutrons'])
        var1.set(df.loc[86,'AtomicNumber'])
        var2.set(df.loc[86,'Element'])
        var3.set(round(df.loc[86,'AtomicMass'],5))
        var4.set('Alkaline\nEarthMetal')
    def ra():
        details_label()
        var5.set(df.loc[87,'Phase'])
        var6.set(df.loc[87,'NumberofNeutrons'])
        var1.set(df.loc[87,'AtomicNumber'])
        var2.set(df.loc[87,'Element'])
        var3.set(round(df.loc[87,'AtomicMass'],5))
        var4.set(df.loc[87,'Type'])
    def ac():
        details_label()
        var5.set(df.loc[88,'Phase'])
        var6.set(df.loc[88,'NumberofNeutrons'])
        var1.set(df.loc[88,'AtomicNumber'])
        var2.set(df.loc[88,'Element'])
        var3.set(round(df.loc[88,'AtomicMass'],5))
        var4.set(df.loc[88,'Type'])
    def th():
        details_label()
        var5.set(df.loc[89,'Phase'])
        var6.set(df.loc[89,'NumberofNeutrons'])
        var1.set(df.loc[89,'AtomicNumber'])
        var2.set(df.loc[89,'Element'])
        var3.set(round(df.loc[89,'AtomicMass'],5))
        var4.set(df.loc[89,'Type'])
    def pa():
        details_label()
        var5.set(df.loc[90,'Phase'])
        var6.set(df.loc[90,'NumberofNeutrons'])
        var1.set(df.loc[90,'AtomicNumber'])
        var2.set('Protacti-\nnium')
        var3.set(round(df.loc[90,'AtomicMass'],5))
        var4.set(df.loc[90,'Type'])
    def u():
        details_label()
        var5.set(df.loc[91,'Phase'])
        var6.set(df.loc[91,'NumberofNeutrons'])
        var1.set(df.loc[91,'AtomicNumber'])
        var2.set(df.loc[91,'Element'])
        var3.set(round(df.loc[91,'AtomicMass'],5))
        var4.set(df.loc[91,'Type'])
    def Np():
        details_label()
        var5.set(df.loc[92,'Phase'])
        var6.set(df.loc[92,'NumberofNeutrons'])
        var1.set(df.loc[92,'AtomicNumber'])
        var2.set(df.loc[92,'Element'])
        var3.set(round(df.loc[92,'AtomicMass'],5))
        var4.set(df.loc[92,'Type'])
    def pu():
        details_label()
        var5.set(df.loc[93,'Phase'])
        var6.set(df.loc[93,'NumberofNeutrons'])
        var1.set(df.loc[93,'AtomicNumber'])
        var2.set(df.loc[93,'Element'])
        var3.set(round(df.loc[93,'AtomicMass'],5))
        var4.set(df.loc[93,'Type'])
    def am():
        details_label()
        var5.set(df.loc[94,'Phase'])
        var6.set(df.loc[94,'NumberofNeutrons'])
        var1.set(df.loc[94,'AtomicNumber'])
        var2.set(df.loc[94,'Element'])
        var3.set(round(df.loc[94,'AtomicMass'],5))
        var4.set(df.loc[94,'Type'])
    def cm():
        details_label()
        var5.set(df.loc[95,'Phase'])
        var6.set(df.loc[95,'NumberofNeutrons'])
        var1.set(df.loc[95,'AtomicNumber'])
        var2.set(df.loc[95,'Element'])
        var3.set(round(df.loc[95,'AtomicMass'],5))
        var4.set(df.loc[95,'Type'])
    def bk():
        details_label()
        var5.set(df.loc[96,'Phase'])
        var6.set(df.loc[96,'NumberofNeutrons'])
        var1.set(df.loc[96,'AtomicNumber'])
        var2.set(df.loc[96,'Element'])
        var3.set(round(df.loc[96,'AtomicMass'],5))
        var4.set(df.loc[96,'Type'])
    def cf():
        details_label()
        var5.set(df.loc[97,'Phase'])
        var6.set(df.loc[97,'NumberofNeutrons'])
        var1.set(df.loc[97,'AtomicNumber'])
        var2.set(df.loc[97,'Element'])
        var3.set(round(df.loc[97,'AtomicMass'],5))
        var4.set(df.loc[97,'Type'])
    def es():
        details_label()
        var5.set(df.loc[98,'Phase'])
        var6.set(df.loc[98,'NumberofNeutrons'])
        var1.set(df.loc[98,'AtomicNumber'])
        var2.set(df.loc[98,'Element'])
        var3.set(round(df.loc[98,'AtomicMass'],5))
        var4.set(df.loc[98,'Type'])
    def fm():
        details_label()
        var5.set(df.loc[99,'Phase'])
        var6.set(df.loc[99,'NumberofNeutrons'])
        var1.set(df.loc[99,'AtomicNumber'])
        var2.set(df.loc[99,'Element'])
        var3.set(round(df.loc[99,'AtomicMass'],5))
        var4.set(df.loc[99,'Type'])
    def md():
        details_label()
        var5.set(df.loc[100,'Phase'])
        var6.set(df.loc[100,'NumberofNeutrons'])
        var1.set(df.loc[100,'AtomicNumber'])
        var2.set('Mendele-\nvium')
        var3.set(round(df.loc[100,'AtomicMass'],5))
        var4.set(df.loc[100,'Type'])
    def No():
        details_label()
        var5.set(df.loc[101,'Phase'])
        var6.set(df.loc[101,'NumberofNeutrons'])
        var1.set(df.loc[101,'AtomicNumber'])
        var2.set(df.loc[101,'Element'])
        var3.set(round(df.loc[101,'AtomicMass'],5))
        var4.set(df.loc[101,'Type'])
    def lr():
        details_label()
        var5.set(df.loc[102,'Phase'])
        var6.set(df.loc[102,'NumberofNeutrons'])
        var1.set('Lawren-\ncium')
        var2.set(df.loc[102,'Element'])
        var3.set(round(df.loc[102,'AtomicMass'],5))
        var4.set(df.loc[102,'Type'])
    def rf():
        details_label()
        var5.set(df.loc[103,'Phase'])
        var6.set(df.loc[103,'NumberofNeutrons'])
        var1.set(df.loc[103,'AtomicNumber'])
        var2.set('Ruther-\nFordium')
        var3.set(round(df.loc[103,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def db():
        details_label()
        var5.set(df.loc[104,'Phase'])
        var6.set(df.loc[104,'NumberofNeutrons'])
        var1.set(df.loc[104,'AtomicNumber'])
        var2.set(df.loc[104,'Element'])
        var3.set(round(df.loc[104,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def sg():
        details_label()
        var5.set(df.loc[105,'Phase'])
        var6.set(df.loc[105,'NumberofNeutrons'])
        var1.set(df.loc[105,'AtomicNumber'])
        var2.set(df.loc[105,'Element'])
        var3.set(round(df.loc[105,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def bh():
        details_label()
        var5.set(df.loc[106,'Phase'])
        var6.set(df.loc[106,'NumberofNeutrons'])
        var1.set(df.loc[106,'AtomicNumber'])
        var2.set(df.loc[106,'Element'])
        var3.set(round(df.loc[106,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def hs():
        details_label()
        var5.set(df.loc[107,'Phase'])
        var6.set(df.loc[107,'NumberofNeutrons'])
        var1.set(df.loc[107,'AtomicNumber'])
        var2.set(df.loc[107,'Element'])
        var3.set(round(df.loc[107,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def mt():
        details_label()
        var5.set(df.loc[108,'Phase'])
        var6.set(df.loc[108,'NumberofNeutrons'])
        var1.set(df.loc[108,'AtomicNumber'])
        var2.set(df.loc[108,'Element'])
        var3.set(round(df.loc[108,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def ds():
        details_label()
        var5.set(df.loc[109,'Phase'])
        var6.set(df.loc[109,'NumberofNeutrons'])
        var1.set(df.loc[109,'AtomicNumber'])
        var2.set('Darmastad-\ntium')
        var3.set(round(df.loc[109,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def rg():
        details_label()
        var5.set(df.loc[110,'Phase'])
        var6.set(df.loc[110,'NumberofNeutrons'])
        var1.set(df.loc[110,'AtomicNumber'])
        var2.set('Roentge-\nnium')
        var3.set(round(df.loc[110,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def cn():
        details_label()
        var5.set(df.loc[111,'Phase'])
        var6.set(df.loc[111,'NumberofNeutrons'])
        var1.set(df.loc[111,'AtomicNumber'])
        var2.set('Coperni-\ncium')
        var3.set(round(df.loc[111,'AtomicMass'],5))
        var4.set('Transition\nMetal')
    def nh():
        details_label()
        var5.set(df.loc[112,'Phase'])
        var6.set(df.loc[112,'NumberofNeutrons'])
        var1.set(df.loc[112,'AtomicNumber'])
        var2.set(df.loc[112,'Element'])
        var3.set(round(df.loc[112,'AtomicMass'],5))
        var4.set('Transac-\ntinide')
    def fi():
        details_label()
        var5.set(df.loc[113,'Phase'])
        var6.set(df.loc[113,'NumberofNeutrons'])
        var1.set(df.loc[113,'AtomicNumber'])
        var2.set(df.loc[113,'Element'])
        var3.set(round(df.loc[113,'AtomicMass'],5))
        var4.set('Transac-\ntinide')
    def mc():
        details_label()
        var5.set(df.loc[114,'Phase'])
        var6.set(df.loc[114,'NumberofNeutrons'])
        var1.set(df.loc[114,'AtomicNumber'])
        var2.set(df.loc[114,'Element'])
        var3.set(round(df.loc[114,'AtomicMass'],5))
        var4.set('Transac-\ntinide')
    def lv():
        details_label()
        var5.set(df.loc[115,'Phase'])
        var6.set(df.loc[115,'NumberofNeutrons'])
        var1.set(df.loc[115,'AtomicNumber'])
        var2.set('Livermo-\nrium')
        var3.set(round(df.loc[115,'AtomicMass'],5))
        var4.set('Transac-\ntinide')
    def ts():
        details_label()
        var5.set(df.loc[116,'Phase'])
        var6.set(df.loc[116,'NumberofNeutrons'])
        var1.set(df.loc[116,'AtomicNumber'])
        var2.set(df.loc[116,'Element'])
        var3.set(round(df.loc[116,'AtomicMass'],5))
        var4.set('Transac-\ntinide')
    def og():
        details_label()
        var5.set(df.loc[117,'Phase'])
        var6.set(df.loc[117,'NumberofNeutrons'])
        var1.set(df.loc[117,'AtomicNumber'])
        var2.set(df.loc[117,'Element'])
        var3.set(round(df.loc[117,'AtomicMass'],5))
        var4.set(df.loc[117,'Type'])


    no_label = Label(root,textvariable=no,font='Times 12 bold', fg='black',height=2,width=5).grid(row=1,column=5)
    name_label = Label(root,textvariable=name,font='Times 12 bold', fg='black',height=2,width=5).grid(row=1,column=7)
    mass_label = Label(root,textvariable=mass,font='Times 12 bold', fg='black',height=2,width=5).grid(row=1,column=9)
    nature_label = Label(root,textvariable=nature,font='Times 12 bold', fg='black',height=2,width=5).grid(row=2,column=5)
    phase_lbl = Label(root,textvariable=phase,font='Times 12 bold', fg='black',height=2,width=5).grid(row=2,column=7)
    neutrons_lbl = Label(root,textvariable=neutrons,font='Times 12 bold', fg='black',height=2,width=5).grid(row=2,column=9)


    label1 = Label(root,textvariable=var1,font='Times 12',bg='black', fg='white',height=2,width=7).grid(row=1,column=6)
    label2 = Label(root,textvariable=var2,font='Times 12',bg='black', fg='white',height=2,width=7).grid(row=1,column=8)
    label3 = Label(root,textvariable=var3,font='Times 12',bg='black', fg='white',height=2,width=7).grid(row=1,column=10)
    label4 = Label(root,textvariable=var4,font='Times 12',bg='black', fg='white',height=2,width=7).grid(row=2,column=6)
    label5 = Label(root,textvariable=var5,font='Times 12',bg='black', fg='white',height=2,width=7).grid(row=2,column=8)
    label6 = Label(root,textvariable=var6,font='Times 12',bg='black', fg='white',height=2,width=7).grid(row=2,column=10)

    lanthenoid_label = Label(root,text='*',font='Times 12 bold', fg='black',height=1,width=4).grid(row=9,column=4)
    acttinoid_label = Label(root,text='**',font='Times 12 bold', fg='black',height=1,width=4).grid(row=10,column=4)

    grp_period_label = Label(root,font='Times 12 bold',text='\nGroup\nPeriod',height=4,width=7).grid(row=0,column=0)

    period_label_1 = Label(root,text='1',font='Times 12 bold', fg='black',height=1,width=1).grid(row=1,column=0)
    period_label_2 = Label(root,text='2',font='Times 12 bold', fg='black',height=1,width=4).grid(row=2,column=0)
    period_label_3 = Label(root,text='3',font='Times 12 bold', fg='black',height=1,width=4).grid(row=3,column=0)
    period_label_4 = Label(root,text='4',font='Times 12 bold', fg='black',height=1,width=4).grid(row=4,column=0)
    period_label_5 = Label(root,text='5',font='Times 12 bold', fg='black',height=1,width=4).grid(row=5,column=0)
    period_label_6 = Label(root,text='6',font='Times 12 bold', fg='black',height=1,width=4).grid(row=6,column=0)
    period_label_7 = Label(root,text='7',font='Times 12 bold', fg='black',height=1,width=4).grid(row=7,column=0)


    group_label_1 = Label(root,text='1',font='Times 12 bold', fg='black',height=2,width=4).grid(row=0,column=1)
    group_label_2 = Label(root,text='2',font='Times 12 bold', fg='black',height=2,width=4).grid(row=1,column=2)
    group_label_3 = Label(root,text='3',font='Times 12 bold', fg='black',height=2,width=4).grid(row=3,column=3)
    group_label_4 = Label(root,text='4',font='Times 12 bold', fg='black',height=2,width=4).grid(row=3,column=4)
    group_label_5 = Label(root,text='5',font='Times 12 bold', fg='black',height=2,width=4).grid(row=3,column=5)
    group_label_6 = Label(root,text='6',font='Times 12 bold', fg='black',height=2,width=4).grid(row=3,column=6)
    group_label_7 = Label(root,text='7',font='Times 12 bold', fg='black',height=2,width=4).grid(row=3,column=7)
    group_label_8 = Label(root,text='8',font='Times 12 bold', fg='black',height=2,width=4).grid(row=3,column=8)
    group_label_9 = Label(root,text='9',font='Times 12 bold', fg='black',height=2,width=4).grid(row=3,column=9)
    group_label_10 = Label(root,text='10',font='Times 12 bold', fg='black',height=2,width=4).grid(row=3,column=10)
    group_label_11 = Label(root,text='11',font='Times 12 bold', fg='black',height=2,width=4).grid(row=3,column=11)
    group_label_12 = Label(root,text='12',font='Times 12 bold', fg='black',height=2,width=4).grid(row=3,column=12)
    group_label_13 = Label(root,text='13',font='Times 12 bold', fg='black',height=2,width=4).grid(row=1,column=13)
    group_label_14 = Label(root,text='14',font='Times 12 bold', fg='black',height=2,width=4).grid(row=1,column=14)
    group_label_15 = Label(root,text='15',font='Times 12 bold', fg='black',height=2,width=4).grid(row=1,column=15)
    group_label_16 = Label(root,text='16',font='Times 12 bold', fg='black',height=2,width=4).grid(row=1,column=16)
    group_label_17 = Label(root,text='17',font='Times 12 bold', fg='black',height=2,width=4).grid(row=1,column=17)
    group_label_18 = Label(root,text='18',font='Times 12 bold', fg='black',height=2,width=4).grid(row=0,column=18)



    button00 = Button(root, text='H',font='Times 20', bg='darkorange', fg='black', height=1, width=4, command=h).grid(row=1,column=1)
    button10 = Button(root, text='Li',font='Times 20', bg='#FFE4B5', fg='black', height=1, width=4, command=li).grid(row=2,column=1)
    button20 = Button(root, text='Na',font='Times 20', bg='#FFE4B5', fg='black', height=1, width=4, command=na).grid(row=3,column=1)
    button30 = Button(root, text='K',font='Times 20', bg='#FFE4B5', fg='black', height=1, width=4, command=k).grid(row=4,column=1)
    button40 = Button(root, text='Rb',font='Times 20', bg='#FFE4B5', fg='black', height=1, width=4, command=rb).grid(row=5,column=1)
    button50 = Button(root, text='Cs',font='Times 20', bg='#FFE4B5', fg='black', height=1, width=4, command=cs).grid(row=6,column=1)
    button60 = Button(root, text='Fr',font='Times 20', bg='#FFE4B5', fg='black', height=1, width=4, command=fr).grid(row=7,column=1)

    button11 = Button(root, text='Be',font='Times 20', bg='#F4A460', fg='black', height=1, width=4, command=be).grid(row=2,column=2)
    button21 = Button(root, text='Mg',font='Times 20', bg='#F4A460', fg='black', height=1, width=4, command=mg).grid(row=3,column=2)
    button31 = Button(root, text='Ca',font='Times 20', bg='#F4A460', fg='black', height=1, width=4, command=ca).grid(row=4,column=2)
    button41 = Button(root, text='Sr',font='Times 20', bg='#F4A460', fg='black', height=1, width=4, command=sr).grid(row=5,column=2)
    button51 = Button(root, text='Ba',font='Times 20', bg='#F4A460', fg='black', height=1, width=4, command=ba).grid(row=6,column=2)
    button61 = Button(root, text='Ra',font='Times 20', bg='#F4A460', fg='black', height=1, width=4, command=ra).grid(row=7,column=2)

    button32 = Button(root, text='Sc',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=sc).grid(row=4,column=3)
    button42 = Button(root, text='Y',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=y).grid(row=5,column=3)
    label111 = Label(root, text='*',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4).grid(row=6,column=3)
    label122 = Label(root, text='**',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4).grid(row=7,column=3)

    button33 = Button(root, text='Ti',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=ti)
    button33.grid(row=4,column=4)
    button43 = Button(root, text='Zr',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=zr).grid(row=5,column=4)
    button53 = Button(root, text='Hf',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=hf).grid(row=6,column=4)
    button63 = Button(root, text='Rf',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=rf).grid(row=7,column=4)

    button34 = Button(root, text='V',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=v).grid(row=4,column=5)
    button44 = Button(root, text='Nb',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=nb).grid(row=5,column=5)
    button54 = Button(root, text='Ta',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=ta).grid(row=6,column=5)
    button64 = Button(root, text='Db',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=db).grid(row=7,column=5)

    button35 = Button(root, text='Cr',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=cr).grid(row=4,column=6)
    button45 = Button(root, text='Mo',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=mo).grid(row=5,column=6)
    button55 = Button(root, text='W',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=w).grid(row=6,column=6)
    button65 = Button(root, text='Sg',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=sg).grid(row=7,column=6)

    button36 = Button(root, text='Mn',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=mn).grid(row=4,column=7)
    button46 = Button(root, text='Tc',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=tc).grid(row=5,column=7)
    button56 = Button(root, text='Re',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=Re).grid(row=6,column=7)
    button66 = Button(root, text='Bh',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=bh).grid(row=7,column=7)

    button37 = Button(root, text='Fe',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=fe).grid(row=4,column=8)
    button47 = Button(root, text='Ru',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=ru).grid(row=5,column=8)
    button57 = Button(root, text='Os',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=Os).grid(row=6,column=8)
    button67 = Button(root, text='Hs',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=hs).grid(row=7,column=8)

    button38 = Button(root, text='Co',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=co).grid(row=4,column=9)
    button48 = Button(root, text='Rh',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=rh).grid(row=5,column=9)
    button58 = Button(root, text='Ir',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=ir).grid(row=6,column=9)
    button68 = Button(root, text='Mt',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=mt).grid(row=7,column=9)

    button39 = Button(root, text='Ni',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=ni).grid(row=4,column=10)
    button49 = Button(root, text='Pd',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=Pd).grid(row=5,column=10)
    button59 = Button(root, text='Pt',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=pt).grid(row=6,column=10)
    button69 = Button(root, text='Ds',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=ds).grid(row=7,column=10)

    button3_10 = Button(root, text='Cu',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=cu).grid(row=4,column=11)
    button4_10 = Button(root, text='Ag',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=ag).grid(row=5,column=11)
    button5_10 = Button(root, text='Au',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=au).grid(row=6,column=11)
    button6_10 = Button(root, text='Rg',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=rg).grid(row=7,column=11)

    button3_11 = Button(root, text='Zn',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=zn).grid(row=4,column=12)
    button4_11 = Button(root, text='Cd',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=cd).grid(row=5,column=12)
    button5_11 = Button(root, text='Hg',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=hg).grid(row=6,column=12)
    button6_11 = Button(root, text='Cn',font='Times 20', bg='#9370DB', fg='black', height=1, width=4, command=cn).grid(row=7,column=12)

    button1_12= Button(root, text='B',font='Times 20', bg='cyan', fg='black', height=1, width=4, command=b).grid(row=2,column=13)
    button2_12 = Button(root, text='Al',font='Times 20', bg='pink', fg='black', height=1, width=4, command=al).grid(row=3,column=13)
    button3_12 = Button(root, text='Ga',font='Times 20', bg='pink', fg='black', height=1, width=4, command=ga).grid(row=4,column=13)
    button4_12 = Button(root, text='In',font='Times 20', bg='pink', fg='black', height=1, width=4, command=In).grid(row=5,column=13)
    button5_12 = Button(root, text='Ti',font='Times 20', bg='pink', fg='black', height=1, width=4, command=ti).grid(row=6,column=13)
    button6_12 = Button(root, text='Nh',font='Times 20', bg='pink', fg='black', height=1, width=4, command=nh).grid(row=7,column=13)

    button1_13 = Button(root, text='C',font='Times 20', bg='darkorange', fg='black', height=1, width=4, command=c).grid(row=2,column=14)
    button2_13 = Button(root, text='Si',font='Times 20', bg='cyan', fg='black', height=1, width=4, command=si).grid(row=3,column=14)
    button3_13 = Button(root, text='Ge',font='Times 20', bg='cyan', fg='black', height=1, width=4, command=ge).grid(row=4,column=14)
    button4_13 = Button(root, text='Sn',font='Times 20', bg='pink', fg='black', height=1, width=4, command=sn).grid(row=5,column=14)
    button5_13 = Button(root, text='Pb',font='Times 20', bg='pink', fg='black', height=1, width=4, command=pb).grid(row=6,column=14)
    button6_13 = Button(root, text='Fi',font='Times 20', bg='pink', fg='black', height=1, width=4, command=fi).grid(row=7,column=14)

    button1_14 = Button(root, text='N',font='Times 20', bg='darkorange', fg='black', height=1, width=4, command=n).grid(row=2,column=15)
    button2_14 = Button(root, text='P',font='Times 20', bg='darkorange', fg='black', height=1, width=4, command=p).grid(row=3,column=15)
    button3_14 = Button(root, text='As',font='Times 20', bg='cyan', fg='black', height=1, width=4, command=ars).grid(row=4,column=15)
    button4_14 = Button(root, text='Sb',font='Times 20', bg='cyan', fg='black', height=1, width=4, command=sb).grid(row=5,column=15)
    button5_14 = Button(root, text='Bi',font='Times 20', bg='pink', fg='black', height=1, width=4, command=bi).grid(row=6,column=15)
    button6_14 = Button(root, text='Mc',font='Times 20', bg='pink', fg='black', height=1, width=4, command=mc).grid(row=7,column=15)

    button1_15 = Button(root, text='O',font='Times 20', bg='darkorange', fg='black', height=1, width=4, command=o).grid(row=2,column=16)
    button2_15 = Button(root, text='S',font='Times 20', bg='darkorange', fg='black', height=1, width=4, command=s).grid(row=3,column=16)
    button3_15 = Button(root, text='Se',font='Times 20', bg='darkorange', fg='black', height=1, width=4, command=se).grid(row=4,column=16)
    button4_15 = Button(root, text='Te',font='Times 20', bg='cyan', fg='black', height=1, width=4, command=te).grid(row=5,column=16)
    button5_15 = Button(root, text='Po',font='Times 20', bg='cyan', fg='black', height=1, width=4, command=po).grid(row=6,column=16)
    button6_15 = Button(root, text='Lv',font='Times 20', bg='pink', fg='black', height=1, width=4, command=lv).grid(row=7,column=16)

    button1_16 = Button(root, text='F',font='Times 20', bg='#3CB371', fg='black', height=1, width=4, command=f).grid(row=2,column=17)
    button2_16 = Button(root, text='Cl',font='Times 20', bg='#3CB371', fg='black', height=1, width=4, command=cl).grid(row=3,column=17)
    button3_16 = Button(root, text='Br',font='Times 20', bg='#3CB371', fg='black', height=1, width=4, command=br).grid(row=4,column=17)
    button4_16 = Button(root, text='I',font='Times 20', bg='#3CB371', fg='black', height=1, width=4, command=i).grid(row=5,column=17)
    button5_16 = Button(root, text='At',font='Times 20', bg='#3CB371', fg='black', height=1, width=4, command=at).grid(row=6,column=17)
    button6_16 = Button(root, text='Ts',font='Times 20', bg='#3CB371', fg='black', height=1, width=4, command=ts).grid(row=7,column=17)

    button0_17 = Button(root, text='He',font='Times 20', bg='gray', fg='black', height=1, width=4, command=he).grid(row=1,column=18)
    button1_17 = Button(root, text='ne',font='Times 20', bg='gray', fg='black', height=1, width=4, command=Ne).grid(row=2,column=18)
    button2_17 = Button(root, text='Ar',font='Times 20', bg='gray', fg='black', height=1, width=4, command=ar).grid(row=3,column=18)
    button3_17 = Button(root, text='Kr',font='Times 20', bg='gray', fg='black', height=1, width=4, command=kr).grid(row=4,column=18)
    button4_17 = Button(root, text='Xe',font='Times 20', bg='gray', fg='black', height=1, width=4, command=xe).grid(row=5,column=18)
    button5_17 = Button(root, text='Rn',font='Times 20', bg='gray', fg='black', height=1, width=4, command=rn).grid(row=6,column=18)
    button6_17 = Button(root, text='Og',font='Times 20', bg='gray', fg='black', height=1, width=4, command=og).grid(row=7,column=18)

    label_star = Label(root,text='*',font='Times 20',fg='black', height=1, width=4).grid(row=9,column=3)
    label_double_star = Label(root,text='**',font='Times 20',fg='black', height=1, width=4).grid(row=10,column=3)

    button83 = Button(root, text='La',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=la).grid(row=9,column=4)
    button84 = Button(root, text='Ce',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=ce).grid(row=9,column=5)
    button85 = Button(root, text='Pr',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=pr).grid(row=9,column=6)
    button86 = Button(root, text='Nd',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=nd).grid(row=9,column=7)
    button8_7 = Button(root, text='Pm',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=pm).grid(row=9,column=8)
    button8_8 = Button(root, text='Sm',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=sm).grid(row=9,column=9)
    button8_9 = Button(root, text='Eu',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=eu).grid(row=9,column=10)
    button8_10 = Button(root, text='Gd',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=gd).grid(row=9,column=11)
    button8_11 = Button(root, text='Tb',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=tb).grid(row=9,column=12)
    button8_12 = Button(root, text='Dy',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=dy).grid(row=9,column=13)
    button8_13 = Button(root, text='Ho',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=ho).grid(row=9,column=14)
    button8_14 = Button(root, text='Er',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=er).grid(row=9,column=15)
    button8_15 = Button(root, text='Tm',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=tm).grid(row=9,column=16)
    button8_16 = Button(root, text='Yb',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=yb).grid(row=9,column=17)
    button8_17 = Button(root, text='Lu',font='Times 20', bg='#FFFF00', fg='black', height=1, width=4, command=lu).grid(row=9,column=18)
    blank_label = Label(root,text='',bg='white',height=1,width=4).grid(row=8,column=1)

    button93 = Button(root, text='Ac',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=ac).grid(row=10,column=4)
    button94 = Button(root, text='Th',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=th).grid(row=10,column=5)
    button95 = Button(root, text='Pa',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=pa).grid(row=10,column=6)
    button96 = Button(root, text='U',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=u).grid(row=10,column=7)
    button97 = Button(root, text='Np',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=nb).grid(row=10,column=8)
    button98 = Button(root, text='Pu',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=pu).grid(row=10,column=9)
    button99 = Button(root, text='Am',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=am).grid(row=10,column=10)
    button9_10 = Button(root, text='Cm',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=cm).grid(row=10,column=11)
    button9_11 = Button(root, text='Bk',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=bk).grid(row=10,column=12)
    button9_12 = Button(root, text='Cf',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=cf).grid(row=10,column=13)
    button9_13 = Button(root, text='Es',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=es).grid(row=10,column=14)
    button9_14 = Button(root, text='Fm',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=fm).grid(row=10,column=15)
    button9_15 = Button(root, text='Md',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=md).grid(row=10,column=16)
    button9_16 = Button(root, text='No',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=No).grid(row=10,column=17)
    button9_17 = Button(root, text='Lr',font='Times 20', bg='#FFA07A', fg='black', height=1, width=4, command=lr).grid(row=10,column=18)
    blank_label = Label(root,text='',bg='white',height=1,width=4).grid(row=11,column=1)
   
    # button for color indication
    label_alkali_metal = Label(root, text='AlkaliMetals',font='Times 10', bg='#FFE4B5', fg='black', height=2, width=9).grid(row=0,column=3)
    label_alkali_earth_metal = Label(root, text='Alkaline\nEarthMetals',font='Times 10', bg='#F4A460', fg='black', height=2, width=9).grid(row=0,column=4)
    label_rare_earth_metals = Label(root, text='Rare-earth\nelements',font='Times 10', bg='#FFFF00', fg='black', height=2, width=9).grid(row=0,column=5)
    label_actinoid = Label(root, text='Actinoids',font='Times 10', bg='#FFA07A', fg='black', height=2, width=9).grid(row=0,column=6)
    label_tarnsition_metal = Label(root, text='Transition\nMetals',font='Times 10', bg='#9370DB', fg='black', height=2, width=9).grid(row=0,column=7)
    label_other_metal = Label(root, text='OtherMetals',font='Times 10', bg='pink', fg='black', height=2, width=9).grid(row=0,column=8)
    label_metalloid = Label(root, text='Metalloids',font='Times 10', bg='cyan', fg='black', height=2, width=9).grid(row=0,column=9)
    label_other_nmetal = Label(root, text='Other\nnon-metals',font='Times 10', bg='darkorange', fg='black', height=2, width=9).grid(row=0,column=10)
    label_halogens = Label(root, text='Halogens',font='Times 10', bg='#3CB371', fg='black', height=2, width=9).grid(row=0,column=11)
    label_nobel_gases = Label(root, text='NobelGases',font='Times 10', bg='gray', fg='white', height=2, width=9).grid(row=0,column=12)

    atomicno_label = Label(root,text='Atomic No. =',font='Times 10 bold',fg='black',height=2,width=9).grid(row=0,column=14)
    protonno_label = Label(root,text=' Proton No. =',font='Times 10 bold',fg='black',height=2,width=9).grid(row=0,column=15)
    electronno_label = Label(root,text=' Electron No.',font='Times 10 bold',fg='black',height=2,width=9).grid(row=0,column=16)

    root.mainloop()
except KeyboardInterrupt:
    sys.exit(0)